y=int(input('Digite um número para saber sua tabuada: '))
print('-'*40)
print(f'{y} x 1= {y}'   )
print(f'{y} x 2 = {y*2}')
print(f'{y} x 3 = {y*3}')
print(f'{y} x 4 = {y*4}')
print(f'{y} x 5 = {y*5}')
print(f'{y} x 6 = {y*6}')
print(f'{y} x 7 = {y*7}')
print(f'{y} x 8 = {y*8}')
print(f'{y} x 9 = {y*9}')
print(f'{y} x 10 = {y*10}')
print('-'*40)
